# Generated by Django 4.2.1 on 2023-11-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(db_column='idCompanion', primary_key=True, serialize=False)),
                ('stateAvailability', models.CharField(choices=[('disponible', 'disponible'), ('no disponible', 'no disponible'), ('pausa', 'pausa')], max_length=20)),
                ('personalDescription', models.TextField()),
            ],
            options={
                'db_table': 'Companion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='idCustomer', primary_key=True, serialize=False)),
                ('accountState', models.CharField(choices=[('Activo', 'Activo'), ('inactivo', 'inactivo')], max_length=20)),
                ('personalPresentation', models.TextField()),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(db_column='idMedicalInformation', primary_key=True, serialize=False)),
                ('allergies', models.TextField()),
                ('medicalConditions', models.TextField()),
                ('medicationIntake', models.TextField()),
                ('medicationRestriction', models.TextField()),
                ('emergencyContact', models.TextField()),
            ],
            options={
                'db_table': 'MedicalInformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(db_column='idReserve', primary_key=True, serialize=False)),
                ('startTime', models.DateField()),
                ('endDate', models.DateField()),
                ('stateReserve', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled')], max_length=45)),
                ('creationDate', models.DateField()),
                ('modality', models.CharField(choices=[('on-site', 'on-site'), ('online', 'online')], max_length=45)),
                ('additionalComment', models.TextField()),
            ],
            options={
                'db_table': 'Reserve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=80)),
                ('lastNames', models.CharField(max_length=80)),
                ('password', models.CharField(editable=False, max_length=255)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('birthDate', models.DateField(null=True)),
                ('genre', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('profilePhoto', models.CharField(max_length=200, null=True)),
                ('registrationDate', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
